import Markdown from 'react-markdown'
import React from 'react'

const markdownContent = `# Rediscovering why I always called Brandon Sanderson favorite author has been an eye-opening experience.
Making my way through high school, whenever a teacher or anyone would ask me about my favorite author or novel my default answer would be Brandon Sanderson and The Way of Kings, respectively. Over the years the reason why started to become lost to me. As with many my age, I dropped reading in high school. Looking back now, it’s almost completely my fault; I started taking extremely rigorous courses and just like sleep, reading an easy thing to cut out of my schedule. What took its place were different types of entertainment, I became heavily invested in YouTube and video games. I now know that subconsciously, I was yearning for a good story. My video game tastes more than reflect that, I have never been able to get into more FPS style games (Overwatch being the only exception). Almost all the games I played were story driven RPG’s, exclusively on Nintendo consoles. Truthfully, I’m glad I did, it opened my eyes to the type of story that can be told through such an interactive medium. Whether that be Xenoblade Chronicles or Phoenix Wright, I became immersed in a new world of storytelling. Because of this period of “change” I experience one of my favorite stories of all time, NieR: Automata; a tale of 3 androids and the fate of the world that I hold very close to my heart. I picked up anime around this time too, another wonderful world of amazing stories. I was again amazed at the difference a new medium could make when telling a story; the stories Akane Tsunemori from Psycho Pass and Asuzagua Sakuta from Seishun Buta Yarou have inspired me to take on analytical writing to examine rhetoric, purely due to the love I have for these stories. Throughout all this though my love for reading subsided for, what I thought to be, more accessible forms of entertainment. 
As I progressed through my sophomore year, I saw that the release date for Oathbringer was steadily approaching. Although I had stopped reading, I never stopped following Brandon Sanderson. It was always cool to check the progress bars on the top of his website that indicated far he was in the writing process. I checked the preorder page on Amazon and it was a pretty substantial purchase at the time. Thirty dollars for the preorder certainly didn’t feel cheap at the time. I felt as if I had to prove my dedication to my “favorite author” and I confirmed the preorder. The book came in about a month or so and for the first time I stopped to think about what I was doing. I tried reading the first few pages and I really didn’t understand anything. What business did I have, picking up a 1000+ page book, as the first novel I would read in over two and a half years? I didn’t remember a single thing about the Stormlight Archive, let alone the Cosmere (a consequence of burning through almost the entire cosmere during my middle school years.) So a cycle of frustration began; I would constantly bring Oathbringer to class on a daily basis. It was as if I was saying “hey look at me! I’m smart and I read big books!” I told my teachers that I would finish it over break, only to bring it back and have my bookmark still at page ten. I eventually gave up and but the book in my bookshelf, where it would remain gathering dust for another year and a half. 
My junior year came around and suffice it to say it was probably the worst and most hectic year of my life. I had virtually no free time to myself, slept an average of 5 or 6 hours per night, and stress was at an all-time high. Part of this stress came from my AP Language and Composition class. It was intense and required me to look at writing from a rhetorical perspective. The best thing that came out of this class our teacher telling us to go pick up a book over spring break. I didn’t expect to take her suggestion seriously until looking at my dusty bookshelf. It was embarrassing, looking at how many dusty books I had lying around. I decided to pick a deceptively simple one off the shelf and give it a read, “The Hunger Games” by Suzanne Collins. I’ve had a (not going to say bad) habit of sucking myself into YA series really easily. As I was rereading this book, I was pleasantly surprised to see that, with my newfound eyes of rhetorical analysis, that these books have been so successful for a reason. The rhetoric contained within them is simple and effective, allowing for incredibly easy manipulation of the readers. Soon after, I started The Throne of Glass series. I’m thankful I started with YA; it allowed me to ease into reading much easier. That being said, it wasn’t easy to find time for my newfound hobby, after spring break ended, I lost even more sleep over squeezing in some time to just read. That being said, I did what I could. I continued reading whenever I could, at a steady pace. Slowly, but surely, I was on my way to finally picking up my first Brandon Sanderson novel in years. 
A new Barnes and Nobel had recently opened up in my city. I always went there because I loved the ambiance and it felt like my crowd of people. But Barnes and Nobel was never a place for me to buy new books to read, it now was a place for me to study. Prep books and all the sort, Barnes and Nobel was definitely the place to go due to their wide selection of content. That being said, I had always found myself drawn to the science fiction and fantasy section, seeing what was new. If I was going to purchase a novel, more likely than not, I would go to the YA section to browse the shelves and occasionally pick up a book. That’s when I saw “Mistborn: The Final Empire” sitting on the shelves. Another series I had completely eaten up before but still had no idea why I liked them so much. I decided on a whim to pick it up- it went straight to my bookshelf. That’s where it remained until the start of quarantine. 
My love for anime really hit an all time high during the start of quarantine, it was a constant cycle of finding a new show and loving every second of it. I discovered that a lot of the source material came from Japanese light novels. Up until now, I had mostly been reading just YA, and since the equivalent of YA in Japan were Japanese light novels, I thought to pick one up- somehow, I ended up picking up over 15. The writing style of these books was so fresh and unexpected. They were incredibly easy to read as well- I honestly loved it. Having kickstarted my new found hobby, I decided to browse the shelves for books to re-read. That’s when I saw Mistborn sitting at the bottom of a stack. 
I decided to finally give Misborn a try. It looked pretty unassuming because I had the mass market paperback version. This led me to believe that it was going to be a pretty quick read- I was wrong. A new lesson that reading had now taught me was that the size mass market paperbacks are incredibly misleading and I don’t like them. I remembered close to nothing about any of Sanderson’s work, which made this feel like a fresh read to me. What a read it was. I was completely immersed in Sanderson’s writing. Finishing a book was a high of its own. I loved Sanderson’s simple and descriptive prose, his fleshed out worlds, the wonderful art in his stories; it all felt so real. It was the escape that I had been craving since quarantine started. The rhetorical analysis side of my kicked in and as I read I noticed the how effective Sanderson’s rhetoric is. “My god, that was disgusting”, I thought to myself after reading a certain scene in The Well of Ascension. The book basically reaffirmed my thoughts by saying “yeah man, that was pretty gruesome, even Elend’s disgusted”. Sanderson had a sort of control over me that I was completely unaware of until I actually sat down to think about the text. I loved being manipulated through his use of clever rhetoric. Since reading Mistborn, I’ve started and (almost) finished the Stormlight Archive, the Skyward series, and Mistborn era 1. 
Although YA novels gave me back my love of reading, Sanderson and the fantasy genre really elevated that love and gave me a new hobby. In the end I just want to say thank you to Mr. Sanderson for giving me this gift, I hope to read more nonfiction in the future and really branch out. Thanks to anyone who reads this as well.`


export default function BrandonSanderson1() {
    return (
        <div className="markdown-content">
            <Markdown>{markdownContent}</Markdown>
        </div>
    );
}