import Markdown from 'react-markdown'
import React from 'react'

const markdownContent = `# Fruits Basket second season has shattered my expectations in every conceivable way thus far. 
I originally was going to set out to write something about how I thought season 1 was an enigma to me. And I think I’ll address why I think so to explain why I think second season has been amazing so far.
To be frank I don’t think extremely highly of season 1. This is not to say I think badly of it, otherwise I wouldn’t have finished the series. I thought it was just…average. I know many people think very highly of first season, as judging from MAL, but allow me to explain my thoughts. There were always weird things that irritated me about it. Two things that particularly stand out to me were a very poorly crafted protagonist and how the writing just doesn’t seem to fit the anime at times. 
I originally had a pretty big problem with Torhu Honda and I still do, to a lesser extent. Torhu seems infallible for a majority for season 1. She seemed really out of place in an anime with such deep and cleverly designed characters. I think my problem with her resided in the fact that she seems way too simple at first glance. I couldn’t understand why in an anime, filled with characters with complex motivations and back stories, Torhu’s would be so plain. All of her problems didn’t seem like they were presented in a manner that made the viewer care about them. Like the fact that her mom died; of course, I’m going to feel bad that someone’s mom died. It’s human nature, but I don’t feel bad that Torhu Honda’s mom died, I just feel bad that someone’s mom is dead and the child now doesn’t have a mom. I could never attach such emotions to Torhu because she never seemed to feel grievance over the fact. She was always such an upbeat personality that I could associate the feeling of loss with someone so simple, that didn’t look like she cared enough. 
Secondly, I thought the anime’s writing just didn’t fit with the actual show at times. The most frequent case of this happening is when it felt like it just took itself way too seriously. It unironically felt a lot more dramatic than it needed to be at times. Towards the start of first season, it didn’t do a good job of conveying why this scene should be dramatic. Because the characters didn’t have enough build up or story behind them to warrant it. The writing and animation just felt way too over the top at times for the story that was being told. All of these aspects led me to not think as highly as I have of other anime I have watched. Most of the time these things simply occurred because the audience didn’t really have the insight that the writers had while designing this; it almost feels like they forgot this at times. 
My last gripe with first season was the poor integration of the zodiac into the main story at first. I was thinking, there has to be some cool stuff that the zodiac members have to do with their unique abilities? Turns out I was wrong and all that consisted of was, don’t get hugged by the opposite gender. That’s all! This was a disappointment to me at first because I was thinking, what’s the point of this even being in the story to begin with. They could have easily just excluded the zodiac stuff and it would have all been fine. Keep in mind this is what I thought while watching roughly the first half of the show. 
The best question to ask at this point then would probably be, why did you even watch the show then? And the answer is very straight forward: the characters in this show absolutely phenomenal. I really enjoyed how the second half was almost all backstory and character development for the zodiac members. Every character is mindbogglingly unique and complex. What separates this show from others is that whereas some shows have a few characters, usually the main cast, that have real thought and care put into them. Fruits Basket somehow manages to break the trend of quality over quantity. Every character has a deep meaningful backstory explaining how the “Zodiac Curse” affects them and it is something that really helped me understand why the Zodiac is so crucial to this show. The Zodiac isn’t necessarily important because of the physical alterations its grant its members, but rather because it is the mental chain that ties them down. The chain that forces them to carry a deep burden and sadness around with them. In this regard, Fruits Basket is probably the only anime I have watched that has managed to do this. Even non-zodiac members have a significant portion to play in the story. Overall, I have major respect for Fruits Basket to have pulled this off. It’s amazing that essentially all of first season was build up to the true story displayed in second season. 
Fruits Basket second season managed to fix all those things and add so much more that I could have never expected. It’s almost as if I’m watched the redemption arc of a whole show. This show picked itself off the ground and completely shattered the ceiling in regards to my expectations for it. 
Towards the end of first season I was honestly really happy with how it ended. Ending on a note of redemption and eyes towards the future was a really good look and I was excited to see what direction the show was going to take next. I found it funny when I found myself saying out loud, “LETS GOOOOO” when the first episode of second season started. Deep down, I knew I was really excited to see where this was going to go.
The first important thing that second season fixed is Torhu finally getting properly fleshed out. Torhu in the first season kind of reminded me of all the memes made about Katara in The Last Airbender. She talks on and on about one meaningful topic to the point where it loses all semblance of importance for the character. One thing that I am enjoying about Torhu is that her proper integration into the Soma family. Knowing that she is quickly creating lots of friends and enemies inside the family makes me feel that there is potential for a huge climax, seeing as how much set up is going into Torhu interacting with the Soma’s as a group a lot more. They also give Torhu’s immaturity and over the top character a lot more meaning now. Before it always seemed like comedic relief; on occasion it would act as a way for Yuki and Kyo to get their feelings out. However, this season gives Torhu’s personality a real purpose. Only a person such as her is able to truly liberate the Soma family from the curse. Only a person such as her will be able to connect with all of the family members individually. Finally, they finally gave Torhu meaningful flaws. It seemed really inhuman of her in season one to be able to come out of any situation smiling. It was inhuman that she was just never sad. Now we see that there truly has been something eating at her insides this whole time, and I’m excited to see where this leads. Granted this doesn’t really fix everything, however it does make watching her character a lot more enjoyable.
Seconds season also feels like it really understands what it’s trying to be now. It looks like the directors really learned a lot from first season. Some prominent examples are how they don’t feel the need to break up a serious scene with silly comedic relief that breaks the flow and buildup of the scene. The anime really understands that a much darker and serious tone must be employed at times to get the most out of the scene. The comedic relief is done in a much more natural fashion, as it is with Yuki and Haru. It’s not extremely overly dramatic, like characters are not giving long monologues when they are unnecessary. The anime just feels like it ebbs and flows a lot nicer. 
What would this show be without the Zodiac? Second season makes the purpose of the Zodiac and its members absolutely clear. The Zodiac is more or less, an ingenious story telling device. The Zodiac feels most comparable to aberrations from Monogatari. In both situations, the supernatural is more of a way to explore the characters and why they are the way there are, rather than some evil antagonist. Second season builds upon the dynamics that govern the Zodiac members that were established in season one, with the intended purpose being to clarify a lot of plot points that were either not explored in season one or were not immediately clear in season one. Second season has made the purpose and function of the Zodiac as a plot device clear, and through its execution it’s easy to see that the writers did a wonderful job of integrating the Zodiac into their work. 
Finally, something new that I think second season introduces that really makes the whole anime stand out even more so far, is its depiction of childhood. Second Season makes it painfully obvious, even more than season one, just how much of an impact parents can have on their children. It makes it obvious how even the small things that parents do, can shape a child’s development. Second Season aims to not only entertain, but also educate the audience on children’s mental development. Whether it’s Yuki’s story of neglect and mental abuse or it’s Hiro’s story of acceptance and care, Fruits Basket is a story about how children deserve care and affection so that it doesn’t affect them in a terrible way later on in their lives. 
Fruits Basket has quickly become one of my favorite anime. Although it took a while for me to really get into it, I can confidently say I am very happy I did. Even if I only did mention aspects of Fruits Basket’s story, there are a number of other reasons you should give it watch: the animation is stellar, the soundtrack is rich and extremely well composed, and it is quite funny where it counts. Honestly, in the beginning the reason I wrote this came from my love of the show, but it turned in to something else as I kept writing. It frustrated me how people shy away from this show because its seen as a Shogo, as if the label itself makes it seem inferior. I just want people to watch the show for what it is, and not be turned away from what others see it to be. Thank you for reading!`

export default function FruitsBasket2() {
    return (
        <div className="markdown-content">
            <Markdown>{markdownContent}</Markdown>
        </div>
    );
}