import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Pirata_One, Six_Caps } from 'next/font/google'

const pirataOne = Pirata_One({
  weight: '400',
  subsets: ['latin'],
})

const sixCaps = Six_Caps({
  weight: '400',
  subsets: ['latin'],
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pirataOne.className} ${sixCaps.className} ${inter.className}`}>{children}</body>
    </html>
  );
}
